name: Shell Comands

on: [push]

jobs:
  run-shell-command:
    runs-on: macos-latest
    steps:
      - name: Install xcodeproj ruby gem
        run: sudo gem install xcodeproj
      - name: Install CocoaPods
        run: sudo gem install cocoapods
      - name: Setup CocoaPods
        run: pod setup
      - name: Install pip
        run: sudo easy_install pip
      - name: Install python six package
        run: pip install six
      - name: Set up JDK 8
        run: |
          brew tap AdoptOpenJDK/openjdk
          brew install --cask adoptopenjdk8
      - name: Install Android SDK
        run: brew install --cask adoptopenjdk8
      - name: Set the ANDROID_HOME system environment variable
        run: export ANDROID_HOME=/usr/local/share/android-sdk
      - name: checkout repo
        uses: actions/checkout@v3
      - name: npm install
        run: npm i
      - name: List NativeScript devices
        run: tns device
