name: Shell Comands

on: [push]

jobs:
  run-shell-command:
    runs-on: macos-latest
    steps:
      - name: Install brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew update
          brew doctor
          brew install github
